apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: baw-ingress
  namespace: baw
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - baw.local
      secretName: baw-tls-secret
  rules:
    - host: baw.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080