apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: baw-tls
  namespace: baw
spec:
  secretName: baw-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - baw.local