apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgresql-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: secret/baw/postgresql
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/baw/postgresql
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: secret/baw/postgresql
        property: POSTGRES_DB
    - secretKey: USER_SVC_DB_PASSWORD
      remoteRef:
        key: secret/baw/postgresql
        property: USER_SVC_DB_PASSWORD
    - secretKey: DOG_SVC_DB_PASSWORD
      remoteRef:
        key: secret/baw/postgresql
        property: DOG_SVC_DB_PASSWORD
    - secretKey: RATING_SVC_DB_PASSWORD
      remoteRef:
        key: secret/baw/postgresql
        property: RATING_SVC_DB_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-service-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: user-service-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_PRIVATE_KEY
      remoteRef:
        key: secret/baw/user-service
        property: JWT_PRIVATE_KEY
    - secretKey: JWT_PUBLIC_KEY
      remoteRef:
        key: secret/baw/user-service
        property: JWT_PUBLIC_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dog-service-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: dog-service-secret
    creationPolicy: Owner
  data:
    - secretKey: SEED_OWNER_IDS
      remoteRef:
        key: secret/baw/dog-service
        property: SEED_OWNER_IDS
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: ghcr-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: secret/baw/ghcr
        property: dockerconfigjson