apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baw
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Arroyo75/BAW-backend
    targetRevision: main
    path: charts/baw
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: baw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true