namespace: baw

postgres:
  image: postgres:15-alpine
  storage: 1Gi
  database: postgres

redis:
  image: redis:7-alpine
  storage: 512Mi

userService:
  image: ghcr.io/Arroyo75/baw-user-service
  tag: sha-6ef566e
  port: 8081
  replicas: 1

dogService:
  image: ghcr.io/Arroyo75/baw-dog-service
  tag: sha-ca33703
  port: 8082
  replicas: 1

ratingService:
  image: ghcr.io/Arroyo75/baw-rating-service
  tag: sha-ca33703
  port: 8083
  replicas: 1

apiGateway:
  image: ghcr.io/Arroyo75/baw-api-gateway
  tag: sha-ca33703
  port: 8080
  replicas: 1

frontend:
  image: docker.io/library/baw-frontend
  tag: latest
  port: 80
  replicas: 1

ingress:
  className: nginx
  host: ""

probes:
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 5

securityContext:
  runAsUser: 1001
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true