---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dog-service-secret
  namespace: baw
spec:
  encryptedData:
    SEED_OWNER_IDS: AgAHYVtrduf5v92SFtbeKpKCSWhoGYpVwiV5sXlSjuHz7bDuAtPmwIRT81DBwWpBei4/F/7mdMn7sFceKxtJuAr8h25ZxssrcYBlrtcJgn3eoqNY/8BBCCNWw3+kOFsJA+hZj6qlfE4cTiB23QfP74s2U0uMEW9Kae5BprWm4ZzfzzKykublpNbqEBD1Hwl8s+PAfna4p3xfipxd7ieVl6VbleawsVil4zIzcilWwaJLLirNx9i6M6t7sogUjkrCOzk0L3T9zOK+0o/HqhcuDUCaraQtLaeeffzdzWRVjlTtJ23eognGGQ/2UN6istyYrR7842bsP7tomWZelEMbLfocYPdYoa0jESHIps1/GGkG8OpPW9WUEowQFOFPshDAPI6BQUA19Q7bdJOH9mIy5KkKg4Vk53BTkBtyzAmb9KpU2hCxtwY0bYfuEGA1kLJPTbytQFtRq4uSvt4ibZJrUQC0XnB62YqPH5ISrTOTBivfsagX1Dg7DdmpcqUpHHWNMjhhG6XCPdGXdY/7yPY8Gvn3kQDxfhjwbVJRfyF+0zDCht78jxA7YukXV/8qow0zEhoFCHvwrX3rijQ3PG6x4d9WnhkJ1TStv89ggDwUAgD/BvFTj/Xpmjj37GvQmqxJYmgC3RM0hy4ViTo/cNr/qOFui/U5/YiOlTdw0oSXLtoTu3y03dN413XNbdl4Lyb8VmSvFzlbJuaFxnY9bMCt2EijDt/zs26lpWDK/kciVUpVRhN6wfixPuDh97chbY/40Bd+QSLQyPfRDjhd/sDG0PX/VStP4IDSaT93n/TjdnJarOLP0ddpGsLyl+tT7uWjLAqlVwHwmu2ZpajPyNUAMQ==
  template:
    metadata:
      name: dog-service-secret
      namespace: baw
    type: Opaque
