---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dog-service-secret
  namespace: baw
spec:
  encryptedData:
    SEED_OWNER_IDS: AgCZ/n3tk8+GQ4ueuYbgJ/DAilrFjPgD135Zpza8qMR2clYNHx/a5tlRSBfnfxcRKhvGmGU36ixCdXO3mC7DF+mP5/y224XEQ18Y7mjP98IXjDXTgCAWWZNFYirSqe/B5YY0WomzK/arKtxdV/AixHPBKPf95zZz60B1nRbhlCwUgQA/QJjzPwYsdOSiaVBVjjb4dxaUC33gO3LHHl5QhVBPGtK0praZRwpltEE9OU3X/awmd23aINyzsSj/JbahVvuY0dYnCRxj7jOmsm5Gg2xX3j+IdYheDSfMW5e4h0eRXHHIewZ45cNC/M8TBaLzJeoi71s7RQWNBj2KNSNJm5KQ6Ag4TwKXl6kmJ8SNXzSkR+Vt2VUZSis4myrzhGRmt6uqaVp7z1/ks1N+TYu5eKYqqzcVA3TgvPVmpCCAAs1QDb1p2q8Jq1I6BGqw3WEv5lzWiTaBI9ZNoAithgq2Fm0IBQAsYDCOsxhiXFoF3DU1i/fwyfbwagWqgpA3x06N1XWVFTMqM2O08R8LV46seXDuafyN+QGCwoOaYVmlHyCNAw3nPfvm2tN4It/dkCZe8vW8n239xqNqmF/n3g+QVh1EbvhJrrYA3+aeCMslnwF1gi87VOOVEniJIebKKZU0Ycj1Iww6YFi1Uybnq6s2ozbl28LsYJ1IdXVYop3BRuNBTKt+r2b+28nkEdqZab7IR7ydqlLq70W+G99QMGMiRLxVy5oq/kLsKpgaqUs/UqQIpZe9bcXavdUQni/BjS43RJ8jvetyApy1p0ArTZWkjDumcy0dELoR2Cs8ha36wfS6GYNWgNoGbd3q7/yLvsL0W9g7rcbgdHfchVsgsK2vPQ==
  template:
    metadata:
      name: dog-service-secret
      namespace: baw
    type: Opaque
