---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: baw
spec:
  encryptedData:
    .dockerconfigjson: AgC240+vIW6HdDegr/jf3nj1bGPpu4hBxajtKMF38GCcbwOYiGZSCjD5ABdQcPOlVMaqmGu1KRSyX2FOl5Aczi0T22nUjRJ/cdCueUOwVRG7T0HUs3TI3UmUHexNtdWeQVe3UGOoMbpdFtATmebQ0Nmlv0O87V+qAKXJGFs+EoJMVdyy9EIi4R72JIhE4UQOxu2dlpNEaQY6Sz2uVuJJpioeTGKxe00vMNm4ngolPwXi6uDwY0yvIJlgb1UMINp5TonWDNEnaTOX+fYlPpdt5gxwUVerR13psuyQVTaYhaZ2ibnO7GFcjASj0Hp275cFPsCR1/rQkPNSF0mvtb81+12RqJbpCVX2yCUSLq9LiYSn7WxFvmfpdJN7tWxWIG20D40a3IWYnLuAEEQPSM7fDHbj/OFLAl6A/Wuf6G32ae7UzJXr9Ndv2eKOWX3Rg8EvvRyaCVDbc9qu5L0IWHIccT18cDmlxmWi4sLsrpK6hc1Z06tBwJv/SQgEh56RaLA3TbWX1unyxr/mGxU80ELt0UZEh9hojesQHdHxu6zafeYgnEwDbca25Nf68q7tF9WL3shWRrQkhfI0eYL0fH+R1PS6WTC9lvZdPF1bKY0ubp1P/IhenQwNFRuCqYxQoJQrZPmqsQT9kQh5ynDDONEZWnB2dDlVIzbszsQqRmySpRNikFrLkX+sSL/W27zUNI0f0PSt78Yx/Rl8CBWlnKLhux5Sy6fzWOCn0s/REkl37cl0sP46BiDZSd8rLnSPeNrV3mWoWgGmHcOiSMcN3MAkayu5WysBCsNmzDB/5/3B2qxehmYCflSeouK28WRI3x0ShntFUkw3ZYM29CzT9HMF2YFTB9pwd1YTOf0EH/aSFr2a5rVXVjvBCY0W40x0eusmOnRTAeQzZqzs8ceF5LJhjqTYnTshEaark/8N2utLXl2ebTc=
  template:
    metadata:
      name: ghcr-secret
      namespace: baw
    type: kubernetes.io/dockerconfigjson
