---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: baw
spec:
  encryptedData:
    .dockerconfigjson: AgBG88WQr2vkAtdNLBK55s2Kk31EypLmEmZ7Nq4guMCo/GD+pJblwW1+vV1ICY4IZ6ewdTZ99NBmQhUZMvEXHEYmtjo7QKCr1/X5ppO3yEopPY/J56fm91RjJzKERKNI+S8sPFmW26UwPU65vPIBkmalwqnHrmp5X6X9cm8fQ6zxCw1CmVCTmgt7XU200lU2AmeRxTVaUvsxSyzG6gXOz9qPsaEL2x5cpOu+v0rNyUT1g+2wiqlbFNjNoRkLx+zD1sS4m4h7rgbK9neJx/nTHsOpRd0HuAzCRPqu5rZ/Vz5oCS8wEb8y5fIJa/oWfIzdH+qLnCJgNzb7Jxj/ScsqIOpKD9S4IhMLaUCjARzjL0G4z+3U7MYWM6lzV3cGgz15WAtIAHw4enaHvRFHxzqRd6MHmj8RX3CKnuYqhY65lWg6WNjJqvZlD+UyH1yzTvhuCf2U7RqKW9rGrmXC66j4iG4G5D+dIoGuseasE6wwdIeY9qwpo72OEjTIdJOhx+hZkxw0bg5j1uoxAK1Z7hNrwQyG7OM8MyeFhnFjtogumVKOwdI8U/u+Fk3XvynF3C2rlz1z79wUHN9RZXFWeQZqPGs+FI+8ry3KVob+jsJJCOsuRinozZw+iyS/kOLrS2Ho/F6KdQaQYvEbikgUdU1GBy+mQ5RKYvJW0u8yRaXruggTjKKg7icBeju5giVLZ80KqNCFW8Bo6+w5diiyhNPQCbAsQ0WgmKPz6UTG+qZ3EA7O4YtJPsUEDFT0rjsM0AedV/QYqs12tzMfVCF8mZTltg18wRSLGB+fn8kSGvgLiN7KdUeIgToojqP6j8YOVxAzKtsPb+7znwBq7NoRdZldjEHUUrUsEGZ8Av/8uUDVBwugROSY6Qm7PVpRyb3oI514k3JpNLyFffS1dtgBe8ApZm2MsmdfkWTS8fdc7bxS4/omY/U=
  template:
    metadata:
      name: ghcr-secret
      namespace: baw
    type: kubernetes.io/dockerconfigjson
